source_mysql:
  host: localhost
  port: 3306
  user: root
  password: sunbeam
  database: retail_src

dwh_mysql:
  host: localhost
  port: 3306
  user: root
  password: sunbeam
  database: retaildwh
